workspace(name = "com_github_davido_gerrit_oauth_provider")

load("//:bazlets.bzl", "load_bazlets")

load_bazlets(
    commit = "c15e64db2a87c0453427ff45f79d1ed3899b5d92",
    #local_path = "/home/<user>/projects/bazlets",
)

# Snapshot Plugin API
#load(
#    "@com_googlesource_gerrit_bazlets//:gerrit_api_maven_local.bzl",
#    "gerrit_api_maven_local",
#)

# Load snapshot Plugin API
#gerrit_api_maven_local()

# Release Plugin API
#定义，编译外部包
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
  name = "com_googlesource_gerrit_bazlets",
  remote = "https://gerrit.googlesource.com/bazlets",
  commit = "928c928345646ae958b946e9bbdb462f58dd1384",
)

#load(
 #   "@com_googlesource_gerrit_bazlets//:gerrit_api.bzl",
  #  "gerrit_api",
#)

#gerrit_api()
load("@com_googlesource_gerrit_bazlets//:gerrit_api.bzl", "gerrit_api")
#gerrit_api(version = "3.2.1",
 #          plugin_api_sha1 = "47019cf43ef7e6e8d2d5c0aeba0407d23c93699c",
  #         acceptance_framework_sha1 = "6252cab6d1f76202e57858fcffb428424e90b128")
 #load("@com_googlesource_gerrit_bazlets//:gerrit_api.bzl", "gerrit_api")
gerrit_api(version = "3.3.0-SNAPSHOT")
load(":external_plugin_deps.bzl", "external_plugin_deps")

external_plugin_deps(omit_commons_codec = False)
